name: private_detector
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8.*
  - pip=20.2.*
  - pip:
    - pandas==1.1.5
    - openpyxl==3.0.7
    - protobuf==3.20.1
    - pyyaml
    - tensorflow-macos==2.9
    - tensorflow-metal==0.5.0
    - tensorflow-hub==0.7.0
    - numpy==1.23.5